// Add new games here. If you add a new entry, also add its label to
// GAME_CATEGORY_OVERRIDES below so the sidebar stays accurate.

const games = [
  { label: 'BitLife', url: '/Games/Bitlife/index.html', thumbnail: '../public/thumbnails/Bitlife.jpg' },
  { label: '1v1.LOL', url: '/Games/1v1.lol/index.html', thumbnail: "../public/thumbnails/1v1.jpg" },
  { label: 'Geometry Dash (hacked)', url: '/Games/geodashhacked.html', thumbnail: "../public/thumbnails/images.webp" },
  { label: 'Among Us', url: '/Games/Amongus/index.html', thumbnail: "../public/thumbnails/amongus.jpg" },
  { label: 'Anti Terrorist Rush 3', url: '/Games/atr3/index.html', thumbnail: "../public/thumbnails/atr3.jpg" },
  { label: 'Slope', url: '/Games/slope/index.html', thumbnail: "../public/thumbnails/slope.jpg" },
  { label: 'Clumsy Bird', url: '/Games/clumsy-bird-master/index.html', thumbnail: "../public/thumbnails/ClumsyBird.jpg" },
  { label: 'Cookie Clicker', url: '/Games/Cookie-Clicker-Source-Code-master/index.html', thumbnail: "../public/thumbnails/CookieClicker.jpg" },
  { label: 'Tetris', url: '/Games/canvas-tetris-master/canvas-tetris-master/index.html', thumbnail: "../public/thumbnails/Tetris.webp" },
  { label: 'Save the Doge', url: '/Games/Dog/index.html', thumbnail: "../public/thumbnails/SaveTheDoge.jpg" },
  { label: 'PAC-MAN', url: '/Games/pm.html', thumbnail: "../public/thumbnails/Pacman.png" },
  { label: 'Bee Swarm Simulator', url: '/Games/Bee-Swarm-Simulator/index.html', thumbnail: "../public/thumbnails/BeeSwarmSimulator.jpg" },
  { label: 'Minecraft 1.8.8 (EaglercraftX)', url: '/Games/mc.html', thumbnail: "../public/thumbnails/Minecraft.webp" },
  { label: 'Geometry Dash', url: '/Games/geodash.html', thumbnail: "../public/thumbnails/images.webp" },
  { label: 'Crossy Road', url: '/Games/CrossyRoad/index.html', thumbnail: "../public/thumbnails/CrossyRoad.webp" },
  { label: 'Subway Surfers', url: '/Games/Subway/index.html', thumbnail: "../public/thumbnails/SubwaySurfers.webp" },
  { label: 'Tic Tac Toe', url: '/Games/tic tac toe/index.html', thumbnail: "../public/thumbnails/TicTacToe.png" },
  { label: 'Chrome Dinosaur Game', url: '/Games/dino.html', thumbnail: "../public/thumbnails/ChromeDino.webp" },
  { label: '3D.CITY', url: '/Games/3d.city/index.html', thumbnail: '../public/thumbnails/3d.jpg' },
  { label: 'Particle Clicker', url: '/Games/particleclicker/index.html', thumbnail: "../public/thumbnails/ParticleClicker.webp" },
  { label: 'The House Game', url: '/Games/Thehousegame/the-house-game-gh-pages/index.html', thumbnail: "../public/thumbnails/TheHouseGame.jpg"   },
  { label: 'Cube Engine', url: '/Games/Cube-engine-master/play.htm', thumbnail: "../public/thumbnails/CubeEngine.jpg" },
  { label: 'URL Chess', url: '/Games/URLchess-master/index.html', thumbnail: "../public/thumbnails/URLChess.png" },
  { label: 'Asteroid Game', url: '/Games/asteroids-game-master/index.html', thumbnail: "../public/thumbnails/AsteroidGame.png" },
  { label: 'Puzzle Maker', url: '/Games/Fifteen_puzzle_maker-main/index.html', thumbnail: "../public/thumbnails/PuzzleMaker.png" },
  { label: 'Anime Clicker', url: '/Games/Anime-Clicker-1.0.2-master/index.html', thumbnail: "../public/thumbnails/AnimeClicker.jpg" },
  { label: 'Doge Miner', url: '/Games/doge miner/index.html', thumbnail: "../public/thumbnails/DogeMiner.jpg" },
  { label: 'Slope 2', url: '/Games/Slope 2/index.html', thumbnail: "../public/thumbnails/Slope2.png" },
  { label: 'Getting Over It', url: '/Upgraded/getting-over-it/index.html', thumbnail: "../public/thumbnails/GettingOverIt.jpg" },
  { label: 'Tower Game', url: '/Games/tower_game-master/index.html', thumbnail: "../public/thumbnails/TowerGame.png" },
  { label: 'Stickman Hook', url: '/Games/Stickman-Hook/index.html', thumbnail: "../public/thumbnails/StickmanHook.webp" },
  { label: "World's Hardest Game", url: '/Games/Worlds-Hardest-Game/index.html', thumbnail: "../public/thumbnails/WorldsHardestGame.jpg" },
  { label: 'Bob The Robber', url: '/Games/bob-the-robber-2/index.html', thumbnail: "../public/thumbnails/BobTheRobber.jpg" },
  { label: 'Bedwars', url: '/Games/Bedwars.html', thumbnail: "../public/thumbnails/Bedwars.jpg" },
  { label: 'Pet Simulator X', url: '/Games/psx.html', thumbnail: "../public/thumbnails/PetSimulatorX.jpg" },
  { label: 'Playlist Cover Maker', url: '/Games/playlists-generator-main/index.html', thumbnail: "../public/thumbnails/PlaylistCoverMaker.jpg" },
  { label: 'Block Blast', url: '/Games/blockblast.html', thumbnail: "../public/thumbnails/Blockblast.webp" },
  { label: 'Birthday Guesser', url: '/Games/birthdayguesser.html', thumbnail: "../public/thumbnails/images.png" },
  { label: 'R.E.P.O', url: 'https://xxpwnxxx420lord.github.io/b2/repo.html', thumbnail: "../public/thumbnails/REPO.jpg" },
  { label: 'Bendy an the Ink Machine', url: 'https://xxpwnxxx420lord.github.io/BATIMWeb/', thumbnail: "../public/thumbnails/BendyTheInkMachine.jpg" },
  { label: 'BloodMoney', url: '/Upgraded/bloodmoney/index.html', thumbnail: "../public/thumbnails/BloodMoney.jpg" },
  { label: 'Buckshot Roulette', url: '/Upgraded/buckshot-roulette/index.html', thumbnail: "../public/thumbnails/BuckshotRoulette.jpg" },
  { label: 'Hollow Knight', url: '/Upgraded/hollow knight', thumbnail: "../public/thumbnails/HollowKnight.jpg" },
  { label: 'People Playground', url: 'http://xxpwnxxx420lord.github.io/b2/PeoplePlaygroundBetter.html', thumbnail: "../public/thumbnails/PeoplePlayground.jpg" },
  { label: 'Pizza Tower', url: '/Upgraded/pizza tower', thumbnail: "../public/thumbnails/PizzaTower.jpg" },
  { label: 'Undertale Yellow (fanmade-prequel)', url: '/Upgraded/undertale-yellow', thumbnail: "../public/thumbnails/UndertaleYellow.webp" },
  { label: 'Bad Parenting', url: '/Games/bad parenting/index.html', thumbnail: "../public/thumbnails/BadParenting.jpg" },
  { label: 'Cuphead', url: 'https://xxpwnxxx420lord.github.io/Barnical-Extended-Games/Cup/index.html', thumbnail: "../public/thumbnails/CupHead.jpg" },
  { label: 'FNF', url: 'https://xxpwnxxx420lord.github.io/Barnical-Extended-Games/FNF/index.html', thumbnail: "../public/thumbnails/FNF.png" },
  { label: 'Milkman Karlson', url: 'https://xxpwnxxx420lord.github.io/Barnical-Extended-Games/Milkson-Karlson/index.html', thumbnail: "../public/thumbnails/MilkmanKarlson.jpg" },
  { label: 'Rocket League (shit version)', url: 'https://xxpwnxxx420lord.github.io/Barnical-Extended-Games/rocket-league/index.html', thumbnail: "../public/thumbnails/RocketLeague.jpg" },
  { label: 'SUPERHOT (prototype)', url: 'https://xxpwnxxx420lord.github.io/Barnical-Extended-Games/superhot/index.html', thumbnail: "../public/thumbnails/Superhot.jpg" },
  { label: 'ULTRAKILL', url: 'https://xxpwnxxx420lord.github.io/Barnical-Extended-Games/ULTRAKILL%20Offline%20Download.html', thumbnail: "../public/thumbnails/Ultrakill.jpg" },
  { label: 'Adventures with Anxiety!', url: 'https://xxpwnxxx420lord.github.io/b2/anxiety-gh-pages/index.html', thumbnail: "../public/thumbnails/AdventuresWithAnxiety.png" },
  { label: 'OneShot', url: 'https://67-factory.github.io/oneshotthing/', thumbnail: "../public/thumbnails/Oneshot.jpg" },
  { label: "Sonic 1", url: "https://xxpwnxxx420lord.github.io/gitsgay/Sonic1", thumbnail: "../public/thumbnails/Sonic1.jpg" },
  { label: "Five Nights at Epsteins", url: "https://xxpwnxxx420lord.github.io/gitsgay/FiveNightsateps", thumbnail: "../public/thumbnails/FiveNightsatEpsteins.jpg" },
  {label : "Hollow Knight: Silksong", url : "https://xxpwnxxx420lord.github.io/hollow-knight-silksong/", thumbnail: "../public/thumbnails/Silksong.jpg" },
  {label : "Mario's Madness: D-sides (FNF MOD)", url : "https://xxpwnxxx420lord.github.io/silkysongs/", thumbnail: "../public/thumbnails/MariosMadness.jpg" },
  {label : "Tricky (FNF MOD)", url : "https://barnicalstuff.github.io/tricky/", thumbnail: "../public/thumbnails/Tricky.jpg" },
  {label : "Angry Birds 2", url : "https://barnicalstuff.github.io/angry2/", thumbnail: "../public/thumbnails/AngryBirds2.webp" },
  {label : "Angry Birds Epic", url : "https://barnicalstuff.github.io/EpicWeb/", thumbnail: "../public/thumbnails/AngryBirdsEpic.webp" },
  {label : "kill the ice age baby adventure 2", url : "https://barnicalstuff.github.io/kill-ice-age-baby-adventure-2-/", thumbnail: "../public/thumbnails/KillIceAgeBabyAdventure2.jpg" },
  {label : "Spaceflight Simulator", url : "https://barnicalstuff.github.io/spaceflight-simulator/", thumbnail: "../public/thumbnails/SpaceflightSimulator.webp" },
  {label : "Sonic 2", url : "https://barnicalstuff.github.io/Sonic-2-WASM/", thumbnail: "../public/thumbnails/Sonic2.webp" },
  {label : "Plants vs Zombies", url : "https://barnicalstuff.github.io/pvz/", thumbnail: "../public/thumbnails/download.webp" },
  {label : "60 Seconds", url : "https://barnicalstuff.github.io/Meteor-60-Seconds-Web/", thumbnail: "../public/thumbnails/met.jpg"},
  {label : "Baldi's Basics plus", url : "https://barnicalstuff.github.io/baldiplus/", thumbnail: "../public/thumbnails/BaldiBasicsPlus.jpg" },
  {label : "Anton Blast", url : "https://barnicalstuff.github.io/antonblast/", thumbnail: "../public/thumbnails/AntonBlast.jpg" },
  {label : "FNAF 1", url : "https://xxpwnxxx420lord.github.io/hd_fnaf/1/", thumbnail: "../public/thumbnails/FNAF1.jpg" },
  {label : "FNAF 2", url : "https://xxpwnxxx420lord.github.io/hd_fnaf/2/", thumbnail: "../public/thumbnails/FNAF2.jpg" },
  {label : "FNAF 3", url : "https://xxpwnxxx420lord.github.io/hd_fnaf/3/", thumbnail: "../public/thumbnails/FNAF3.jpg" },
  {label : "FNAF 4", url : "https://xxpwnxxx420lord.github.io/hd_fnaf/4/", thumbnail: "../public/thumbnails/FNAF4.jpg" },
  {label : "FNAF World", url : "https://xxpwnxxx420lord.github.io/hd_fnaf/w/", thumbnail: "../public/thumbnails/FNAFWorld.jpg" },
  {label : "FNAF: Sister location", url : "https://xxpwnxxx420lord.github.io/hd_fnaf/sl/", thumbnail: "../public/thumbnails/FNAFSisterLocation.jpg" },
  {label : "FNAF: Ultimate Custom Night", url : "https://xxpwnxxx420lord.github.io/hd_fnaf/ucn/", thumbnail: "../public/thumbnails/FNAFUltiCustomNight.webp" },
  {label : "Happy Wheels", url : "https://barnicalstuff.github.io/beauty/public/games/happywheels", thumbnail: "../public/thumbnails/HappyWheels.webp" },
  {label : "Jetpack Joyride", url : "https://barnicalstuff.github.io/bbb/jetpack-joyride", thumbnail: "../public/thumbnails/JetpackJoyride.webp" },
  {label : "Pixel Gun Survival", url : "https://barnicalstuff.github.io/bbb/pixel-gun-survival", thumbnail: "../public/thumbnails/PixelGunSurvival.webp" },
  {label : "Backrooms", url : "https://barnicalstuff.github.io/bbb/backrooms", thumbnail: "../public/thumbnails/Backrooms.jpg" },
  {label : "Run 2", url : "https://barnicalstuff.github.io/bbb/run2", thumbnail: "../public/thumbnails/Run2.jpg" },
  {label : "Impossible Quiz", url : "https://barnicalstuff.github.io/bbb/impossiblequiz", thumbnail: "../public/thumbnails/ImpossibleQuiz.webp" },
  {label : "Iron Lung", url : "https://barnicalstuff.github.io/iron-lung", thumbnail: "../public/thumbnails/IronLung.jpg" },
  {label : "Plague Inc. Envolved", url : "https://xxpwnxxx420lord.github.io/PlagueIncEvolved/", thumbnail: "../public/thumbnails/PlagueIncEvolved.webp" },
  {label : "Granny", url : "https://barnicalstuff.github.io/GrannyWeb", thumbnail: "../public/thumbnails/Granny.jpg" },
  {label : "Web Fishing", url : "https://barnicalstuff.github.io/webfishing/", thumbnail: "../public/thumbnails/WebFishing.jpg" },
  {label : "Brotato", url : "https://barnicalstuff.github.io/BrotatoWeb/", thumbnail: "../public/thumbnails/Brotato.jpg" },
  {label : "Shift At Midnight", url : "https://barnicalstuff.github.io/Shift-At-Midnight/", thumbnail: "../public/thumbnails/ShiftAtMidnight.jpg" },
  {label : "Super Mario 64 FPS", url : "https://barnicalstuff.github.io/sm64fps-port/", thumbnail: "../public/thumbnails/SuperMario64FPS.jpg" },
  {label : "Lobotomy Corporation", url : "https://barnicalstuff.github.io/lobcorp/", thumbnail: "../public/thumbnails/LobotomyCorporation.jpg" },
  {label : "Clover Pit", url : "https://barnicalstuff.github.io/Clover-Pit/", thumbnail: "../public/thumbnails/CloverPit.jpg" },
  {label : "Baltro", url : "https://barnicalstuff.github.io/Baltaro/", thumbnail: "../public/thumbnails/Baltaro.jpg" },
  {label : "Binding of Isaac", url : "https://barnicalstuff.github.io/binding-of-isaac/", thumbnail: "../public/thumbnails/BindingOfIsaac.jpg" },
  {label : "Gladihoppers", url : "https://barnicalstuff.github.io/Gladihoppers/", thumbnail: "../public/thumbnails/Gladihoppers.webp" },
  {label : "Nazi Zombies: Portable", url : "https://barnicalstuff.github.io/Nazi-Zombies/", thumbnail: "../public/thumbnails/NaziZombies.jpg" },
  {label : "Jeffery Epstein's Basics in Education and Kidnapping", url : "https://xxpwnxxx420lord.github.io/at/a.html", thumbnail: "../public/thumbnails/JefferyEpsteinBasics.jpg" },
  {label : "Untitled Goose Game", url : "https://xxpwnxxx420lord.github.io/at/", thumbnail: "../public/thumbnails/UntitledGooseGame.jpg" },
  {label : "Mario's Madness V2", url : "https://barnicalstuff.github.io/MariosMadnessV2", thumbnail: "../public/thumbnails/MariosMadnessV2.jpg" },
  {label : "Half Life", url : "https://xxpwnxxx420lord.github.io/at/halflife.html", thumbnail: "../public/thumbnails/HalfLife.webp" },
  {label : "Kirby Squeak Squad", url : "https://xxpwnxxx420lord.github.io/at/squeksquad.html", thumbnail: "../public/thumbnails/KirbySqueakSquad.jpg" },
  {label : "Nut Simulator", url : "https://barnicalstuff.github.io/nutsimulator/index.html", thumbnail: "../public/thumbnails/NutSimulator.jpg" },
  {label : "Online Car Racing Game", url : "https://barnicalstuff.github.io/cars/", thumbnail: "../public/thumbnails/OnlineCarRacingGame.jpg" },
  {label : "Escape Road 3", url : "https://barnicalstuff.github.io/abra/", thumbnail: "../public/thumbnails/EscapeRoad3.jpg" },
  {label : "A Dance Of Fire And Ice", url : "https://barnicalstuff.github.io/beauty/public/games/a-dance-of-fire-and-ice/", thumbnail: "../public/thumbnails/ADanceOfFireAndIce.webp" },
  {label : "Cluster Rush", url : "https://barnicalstuff.github.io/beauty/public/games/cluster/", thumbnail: "../public/thumbnails/ClusterTruck.webp" },
  {label : "Bloxorz", url : "https://barnicalstuff.github.io/beauty/public/games/bloxors/", thumbnail: "../public/thumbnails/Bloxors.webp" },
  {label : "Basket Random", url : "https://barnicalstuff.github.io/beauty/public/games/basket-random", thumbnail: "../public/thumbnails/BasketballRandom.jpg" },
  {label : "Cut the Rope", url : "https://barnicalstuff.github.io/beauty/public/games/cuttherope", thumbnail: "../public/thumbnails/CutTheRope.jpg" },
  {label : "Slow Roads", url : "https://barnicalstuff.github.io/beauty/public/games/slowroads", thumbnail: "../public/thumbnails/SlowRoads.jpg" },
  {label : "Ragdoll Archers", url : "https://barnicalstuff.github.io/beauty/public/games/ragdoll-archers", thumbnail: "../public/thumbnails/RagdollArchers.jpg" },
  {label : "Run", url : "https://barnicalstuff.github.io/beauty/public/games/run", thumbnail: "../public/thumbnails/Run.jpg" },
  {label : "Soccer Random", url : "https://barnicalstuff.github.io/beauty/public/games/soccer-random", thumbnail: "../public/thumbnails/SoccerRandom.jpg" },
  {label : "Paper io 2", url : "https://barnicalstuff.github.io/beauty/public/games/paperio2/", thumbnail: "../public/thumbnails/PaperIo2.jpg" },
  {label : "Monkey Mart", url : "https://barnicalstuff.github.io/beauty/public/games/MonkeyMart", thumbnail: "../public/thumbnails/MonkeyMart.jpg" },
  // about here is the new game section
  {label : "Gamebreaker (FNF MOD)", url : "https://xxpwnxxx420lord.github.io/at/gamebreaker.html", thumbnail: "../public/thumbnails/gamebreaker.jpg" },
  {label : "Survivor.io", url : "https://xxpwnxxx420lord.github.io/at/Survivor.io.html", thumbnail: "../public/thumbnails/Survivor.io.webp" },
  {label : "Fruit Ninja", url : "https://xxpwnxxx420lord.github.io/at/fruitninja.html", thumbnail: "../public/thumbnails/fruitninja.webp" },
  {label : "Fears to Fathom: Home Alone", url : "https://xpxwnxxx420lord.github.io/at/fearstofathom.html", thumbnail: "../public/thumbnails/fearstofathom.jpg" },
  {label : "Megachess", url : "https://xxpwnxxx420lord.github.io/at/megachess.html", thumbnail: "../public/thumbnails/megachess.jpg" },
  {label : "Postal", url : "https://xxpwnxxx420lord.github.io/at/postal.html", thumbnail: "../public/thumbnails/postal.jpg" },
  {label : "Bad Piggies", url : "https://xxpwnxxx420lord.github.io/at/badapples.html", thumbnail: "../public/thumbnails/badapples.webp" },
  {label : "Punch the Trump", url : "https://xxpwnxxx420lord.github.io/at/Punchthetrump.html", thumbnail: "../public/thumbnails/Punchthetrump.jpg" },
  {label : "Dune Dash", url : "https://xxpwnxxx420lord.github.io/at/dunedash.html", thumbnail: "../public/thumbnails/dunedash.jpg" },
  {label : "Volley Random", url : "https://xxpwnxxx420lord.github.io/at/volleyrandom.html", thumbnail: "../public/thumbnails/volleyrandom.jpg" },
  {label : "Trees Hate You", url : "https://xxpwnxxx420lord.github.io/at/treeshateyou.html", thumbnail: "../public/thumbnails/treeshateyou.jpg" },
  {label : "Cat Mario", url : "https://xxpwnxxx420lord.github.io/at/catmario.html", thumbnail: "../public/thumbnails/catmario.jpg" },
  {label : "Tung Tung Horror", url : "https://xxpwnxxx420lord.github.io/at/tungtunghorror.html", thumbnail: "../public/thumbnails/tungtunghorror.jpg" },
  {label : "There Is No Game", url : "https://xxpwnxxx420lord.github.io/at/Thereisnogame.html", thumbnail: "../public/thumbnails/Thereisnogame.jpg" },
  {label : "Eggy car", url : "https://xxpwnxxx420lord.github.io/at/eggycar.html", thumbnail: "../public/thumbnails/eggycar.jpg" },
  {label : "Level Devil", url : "https://xxpwnxxx420lord.github.io/at/leveldevil.html", thumbnail: "../public/thumbnails/leveldevil.webp" },
];

function createGame(label, url, thumbnail, category) {
  return { label, url, thumbnail, category };
}

const GAME_CATEGORY_OVERRIDES = {
  "Bitlife": "simulation",
  "1v1.lol": "action",
  "Geometry dash hacked": "action",
  "Among us": "action",
  "Atr3": "action",
  "Slope": "action",
  "ClumsyBird": "action",
  "Cookie clicker": "simulation",
  "Tetris": "puzzle",
  "Save the doge": "action",
  "Pacman": "arcade",
  "Bee swarm Simulator": "simulation",
  "Minecraft 1.8.8": "adventure",
  "Geometry dash": "action",
  "Crossy Road": "adventure",
  "Subway Surfers": "adventure",
  "Tic Tac Toe": "puzzle",
  "Chrome offline dinoscar game": "action",
  "3d.city": "simulation",
  "Particle clicker": "simulation",
  "The house game": "horror",
  "Cube engine": "puzzle",
  "URL chess": "puzzle",
  "Asteroid game": "action",
  "Puzzle maker": "puzzle",
  "Anime clicker": "simulation",
  "Doge miner": "simulation",
  "Slope 2": "action",
  "Getting over it": "adventure",
  "Tower game": "action",
  "Stickman hook": "action",
  "Worlds hardest game": "action",
  "Bob the robber": "adventure",
  "Bedwars": "action",
  "Pet simulator x": "simulation",
  "Playlist cover maker": "simulation",
  "Blockblast": "puzzle",
  "Birthday guesser": "puzzle",
  "R.E.P.O": "horror",
  "Bendy the ink machine": "horror",
  "BloodMoney": "horror",
  "Buckshot roulette": "horror",
  "Hollow Knight": "adventure",
  "People playground": "simulation",
  "Pizza tower": "adventure",
  "Undertale yellow (fanmade-prequel)": "adventure",
  "Bad Parenting": "horror",
  "Cup Head": "adventure",
  "FNF": "rhythm",
  "Milkman Karlson": "action",
  "Mario": "adventure",
  "Rocket League (shit version)": "sports",
  "Superhot": "action",
  "Ultrakill": "action",
  "Adventures with anxiety": "adventure",
  "Oneshot": "adventure",
  "Sonic 1": "adventure",
  "Five nights at epsteins": "horror",
  "Silksong": "adventure",
  "Mario's Madness (FNF MOD)": "rhythm",
  "Tricky (FNF MOD)": "rhythm",
  "Angry Birds 2": "action",
  "Angry Birds epic": "action",
  "Kill ice age baby adventure 2": "adventure",
  "Spaceflight simulator": "simulation",
  "Sonic 2": "adventure",
  "Plants vs Zombies": "simulation",
  "60 Seconds": "simulation",
  "Baldi basics plus": "horror",
  "Anton Blast": "action",
  "FNAF 1": "horror",
  "FNAF 2": "horror",
  "FNAF 3": "horror",
  "FNAF 4": "horror",
  "FNAF World": "horror",
  "FNAF Sister location": "horror",
  "FNAF Ulti custom night": "horror",
  "Happy Wheels": "action",
  "Jetpack Joyride": "action",
  "Pixel Gun Survival": "action",
  "Backrooms": "horror",
  "Run 2": "action",
  "Impossible quiz": "puzzle",
  "Iron Lung": "horror",
  "Plague Inc Envolved": "simulation",
  "Granny": "horror",
  "Web fishing": "simulation",
  "Brotato": "action",
  "Shift at midnight": "horror",
  "Super mario 64 fps": "adventure",
  "lobotomy corporation": "horror",
  "Clover Pit": "horror",
  "Baltro (kinda laggy)": "puzzle",
  "binding of isaac": "action",
  "Gladihoppers": "action",
  "Nazi Zombies type game": "horror",
  "Jeffery Epsteins Basics in education and kidnapping": "horror",
  "Untitled Goose Game": "adventure",
  "Mario's Madness V2": "rhythm",
  "Half life": "action",
  "Kirby squeak squad": "adventure",
  "Nut simulator": "simulation",
  "Online Car Racing Game": "sports",
  "Escape Road 3": "sports",
  "A dance of fire and ice": "rhythm",
  "Cluster truck": "action",
  "Bloxors": "puzzle",
  "Basketball Random": "sports",
  "Cut the rope": "puzzle",
  "Slow Roads": "sports",
  "Ragdoll Archers": "action",
  "Run": "action",
  "Soccer Random": "sports",
  "Paper io 2": "action",
  "Monkey mart": "simulation",
  "Gamebreaker (FNF MOD)": "rhythm",
  "Survivor.io": "action",
  "Fruit ninja": "action",
  "Fears to Fathom: Home alone": "horror",
  "Megachess": "puzzle",
  "Postal": "action",
  "Bad Piggie": "action",
  "Punch the trump": "action",
  "Dune dash": "action"
};

const CATEGORY_LABELS = {
  all: "All",
  arcade: "Arcade",
  action: "Action",
  puzzle: "Puzzle",
  simulation: "Sim",
  adventure: "Adventure",
  horror: "Horror",
  rhythm: "Rhythm",
  sports: "Sports",
};

const CATEGORY_RULES = [
  {
    category: "horror",
    patterns: [
      /fnaf/i,
      /five nights/i,
      /granny/i,
      /bendy/i,
      /bloodmoney/i,
      /backrooms/i,
      /epstein/i,
      /nazi zombies?/i,
      /bad parenting/i,
      /iron lung/i,
      /repo/i,
      /buckshot roulette/i,
      /shift at midnight/i,
      /lobotomy corporation/i,
      /the house game/i,
      /jeffery epsteins basics/i
    ]
  },
  {
    category: "rhythm",
    patterns: [
      /a dance of fire and ice/i,
      /\bfnf\b/i,
      /Mario's madness/i,
      /Gamebreaker/i,
      /\btricky\b/i
    ]
  },
  {
    category: "puzzle",
    patterns: [
      /tetris/i,
      /tic tac toe/i,
      /url chess/i,
      /puzzle maker/i,
      /bloxors/i,
      /blockblast/i,
      /birthday guesser/i,
      /cut the rope/i,
      /cube engine/i
    ]
  },
  {
    category: "sports",
    patterns: [
      /rocket league/i,
      /fifa/i,
      /soccer random/i,
      /basketball random/i,
      /car racing/i,
      /escape road/i,
      /slow roads/i
    ]
  },
  {
    category: "simulation",
    patterns: [
      /bitlife/i,
      /simulator/i,
      /\bsim\b/i,
      /clicker/i,
      /miner/i,
      /playground/i,
      /city/i,
      /pet simulator/i,
      /people playground/i,
      /bee swarm/i,
      /plague inc/i,
      /web fishing/i,
      /monkey mart/i,
      /playlist cover maker/i,
      /cover maker/i
    ]
  },
  {
    category: "adventure",
    patterns: [
      /getting over it/i,
      /hollow knight/i,
      /undertale/i,
      /oneshot/i,
      /sonic/i,
      /mario/i,
      /cup head/i,
      /adventures with anxiety/i,
      /untitled goose game/i,
      /kirby squeak squad/i,
      /minecraft/i,
      /bob the robber/i,
      /super mario 64 fps/i,
      /kill ice age baby adventure 2/i,
      /crossy road/i,
      /subway surfers/i
    ]
  },
  {
    category: "action",
    patterns: [
      /1v1\.lol/i,
      /Geometry dash/i,
      /Among us/i,
      /Atr3/i,
      /Slope/i,
      /Clumsybird/i,
      /Chrome offline dinoscar game/i,
      /Asteroid game/i,
      /Tower game/i,
      /Bedwars/i,
      /Stickman hook/i,
      /Superhot/i,
      /Gladihoppers/i,
      /Ragdoll archers/i,
      /Paper io 2/i,
      /Run 2/i,
      /^Run$/i,
      /Half life/i,
      /ultrakill/i,
      /milkman karlson/i,
      /baltro/i,
      /cluster truck/i,
      /brotato/i,
      /happy wheels/i
    ]
  }
];

function getGameCategory(game) {
  if (game && typeof game.category === "string" && CATEGORY_LABELS[game.category]) {
    return game.category;
  }

  if (game && GAME_CATEGORY_OVERRIDES[game.label]) {
    return GAME_CATEGORY_OVERRIDES[game.label];
  }

  const text = `${game.label} ${game.url}`.toLowerCase();
  for (const rule of CATEGORY_RULES) {
    if (rule.patterns.some((pattern) => pattern.test(text))) {
      return rule.category;
    }
  }
  return "arcade";
}

const categorizedGames = games.map((game) => ({
  ...game,
  category: GAME_CATEGORY_OVERRIDES[game.label] || getGameCategory(game)
}));

const sortedGames = [...categorizedGames].sort((a, b) =>
  a.label.localeCompare(b.label, undefined, {
    numeric: true,
    sensitivity: "base"
  })
);

// app.js renders everything now - games.js just exposes data + category logic.
window.games = sortedGames;
window.getGameCategory = getGameCategory;
window.CATEGORY_LABELS = CATEGORY_LABELS;
window.GAME_CATEGORY_OVERRIDES = GAME_CATEGORY_OVERRIDES;
window.__games = sortedGames;
