window.onload = function() {
    console.log(`
██╗  ██╗ ██████╗ ██╗     ██████╗     ██╗   ██╗██████╗ ██╗
██║  ██║██╔═══██╗██║     ██╔══██╗    ██║   ██║██╔══██╗██║
███████║██║   ██║██║     ██║  ██║    ██║   ██║██████╔╝██║
██╔══██║██║   ██║██║     ██║  ██║    ██║   ██║██╔═══╝ ╚═╝
██║  ██║╚██████╔╝███████╗██████╔╝    ╚██████╔╝██║     ██╗
╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═════╝      ╚═════╝ ╚═╝     ╚═╝
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]
Why are you trying to execute code [insert name here]

    `);
};
